map("n", "<C-h>", "<C-w>h", "Split links")
map("n", "<C-j>", "<C-w>j", "Split unten")
map("n", "<C-k>", "<C-w>k", "Split oben")
map("n", "<C-l>", "<C-w>l", "Split rechts")
map("n", "<C-Up>", "<cmd>resize +2<cr>", "Split höher")
map("n", "<C-Down>", "<cmd>resize -2<cr>", "Split niedriger")
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", "Split schmaler")
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", "Split breiter")

map("n", "<Esc>", "<cmd>nohlsearch<cr>", "remove search highlighting")
